version: '3.8'
services:
  vae-web:
    build:
      context: .
      dockerfile: dockerfile
    networks:
      - reverse_proxy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1/", ">/dev/null", "2>&1" ]
      interval: 30s
      timeout: 3s
      retries: 3
    # environment:
    #   - NODE_ENV=production

networks:
  reverse_proxy:
    external: true