export type TechCategoryId =
  | 'open-source-ai'
  | 'enterprise-models'
  | 'frameworks'
  | 'backend'
  | 'databases'
  | 'frontend'
  | 'infrastructure'
  | 'data-workflows'
  | 'baas-platforms'
  | 'dev-tools'

export interface TechTile {
  id: string
  name: string
  link: string
  description?: string
  organization?: string
  logo?: string
  category: TechCategoryId
  group?: string
}

export interface TechSection {
  id: TechCategoryId
  heading: string
  subheading?: string
  badge: string
  groups?: Array<{ id: string; title: string; description?: string }>
}

export const TECH_SECTIONS: TechSection[] = [
  {
    id: 'open-source-ai',
    heading: 'KI-Modelle für vielfältige Anwendungsfälle',
    subheading: 'Self-Hosted-First. Unabhängigkeit durch transparente Technologie.',
    badge: 'Section 01 · Hugging Face',
    groups: [
      { id: 'llms', title: 'Large Language Models (LLMs)' },
      { id: 'specialized', title: 'Spezialisierte Modelle' },
      { id: 'embeddings', title: 'Embedding & Vector Models' },
      { id: 'vision', title: 'Vision & Multimodal' },
    ],
  },
  {
    id: 'enterprise-models',
    heading: 'Bewährte KI-Frameworks und Modelle',
    subheading: 'Produktionsreife Lösungen für komplexe Anforderungen.',
    badge: 'Section 02 · Enterprise Models',
  },
  {
    id: 'frameworks',
    heading: 'AI Frameworks & Libraries',
    subheading: 'Von Research bis Production – alles was LLM-Apps braucht.',
    badge: 'Section 03 · Frameworks',
    groups: [
      { id: 'foundation', title: 'Foundation Frameworks' },
      { id: 'llm-app', title: 'LLM Application Frameworks' },
    ],
  },
  {
    id: 'backend',
    heading: 'Backend & API Frameworks',
    subheading: 'APIs, Services, Workflows – stabil und skalierbar.',
    badge: 'Section 04 · Backend',
  },
  {
    id: 'databases',
    heading: 'Databases & Storage',
    subheading: 'Relational, NoSQL, Vektoren – je nach Architektur.',
    badge: 'Section 05 · Datenebene',
    groups: [
      { id: 'relational', title: 'Relational' },
      { id: 'nosql', title: 'NoSQL' },
      { id: 'vector', title: 'Vector & Semantic' },
    ],
  },
  {
    id: 'frontend',
    heading: 'Frontend & Web',
    subheading: 'Schnelle Interfaces, moderne Frameworks, präzises Design.',
    badge: 'Section 06 · Frontend',
  },
  {
    id: 'infrastructure',
    heading: 'Infrastructure & Deployment',
    subheading: 'Von Docker bis Cloud – reproduzierbare Systeme.',
    badge: 'Section 07 · Infrastructure',
  },
  {
    id: 'data-workflows',
    heading: 'Data & Workflow Orchestration',
    subheading: 'Workflows, Scheduling, Automation – deterministisch und nachvollziehbar.',
    badge: 'Section 08 · Workflows',
  },
  {
    id: 'baas-platforms',
    heading: 'Backend-as-a-Service & Platforms',
    subheading: 'Schnelles Prototyping, offene Plattformen, keine Blackbox.',
    badge: 'Section 09 · BaaS & Platforms',
  },
  {
    id: 'dev-tools',
    heading: 'Developer Tools',
    subheading: 'Collaboration, Paket-Ökosysteme, Repositories.',
    badge: 'Section 10 · Dev Tools',
  },
]

export const TECH_FILTERS: Array<{ id: 'all' | TechCategoryId; label: string }> = [
  { id: 'all', label: 'Alle anzeigen' },
  { id: 'open-source-ai', label: 'Open Source AI Models' },
  { id: 'enterprise-models', label: 'Enterprise Models' },
  { id: 'frameworks', label: 'Frameworks & Libraries' },
  { id: 'backend', label: 'Backend' },
  { id: 'databases', label: 'Databases' },
  { id: 'frontend', label: 'Frontend' },
  { id: 'infrastructure', label: 'Infrastructure' },
  { id: 'data-workflows', label: 'Data & Workflows' },
  { id: 'baas-platforms', label: 'BaaS & Platforms' },
  { id: 'dev-tools', label: 'Developer Tools' },
]

export const TECH_TILES: TechTile[] = [
  // Section 1: LLMs
  {
    id: 'llama-2',
    name: 'Llama 2',
    organization: 'Meta',
    description: 'Open Source LLM',
    link: 'https://huggingface.co/meta-llama/Llama-2-70b',
    logo: '/logos/tech/meta-logo.png',
    category: 'open-source-ai',
    group: 'llms',
  },
  {
    id: 'llama-3',
    name: 'Llama 3',
    organization: 'Meta',
    description: 'Neueste Generation',
    link: 'https://huggingface.co/meta-llama/Llama-3-70b',
    logo: '/logos/tech/meta-logo.png',
    category: 'open-source-ai',
    group: 'llms',
  },
  {
    id: 'mistral-7b',
    name: 'Mistral 7B',
    organization: 'Mistral AI',
    description: 'Effizient & schnell',
    link: 'https://huggingface.co/mistralai/Mistral-7B',
    logo: '/logos/tech/mistralai-avatar.png',
    category: 'open-source-ai',
    group: 'llms',
  },
  {
    id: 'mixtral-8x7b',
    name: 'Mixtral 8x7B',
    organization: 'Mistral AI',
    description: 'MoE Architecture',
    link: 'https://huggingface.co/mistralai/Mixtral-8x7B-v0.1',
    logo: '/logos/tech/mistralai-avatar.png',
    category: 'open-source-ai',
    group: 'llms',
  },
  {
    id: 'phi-3',
    name: 'Phi-3',
    organization: 'Microsoft',
    description: 'Edge-optimiert',
    link: 'https://huggingface.co/microsoft/phi-3',
    logo: '/logos/tech/microsoft-seeklogo.png',
    category: 'open-source-ai',
    group: 'llms',
  },
  {
    id: 'qwen-72b',
    name: 'Qwen 72B',
    organization: 'Alibaba',
    description: 'Multilingual',
    link: 'https://huggingface.co/Qwen/Qwen-72B',
    logo: '/logos/tech/alibaba.svg',
    category: 'open-source-ai',
    group: 'llms',
  },
  {
    id: 'falcon-40b',
    name: 'Falcon 40B',
    organization: 'TII',
    description: 'Open & performant',
    link: 'https://huggingface.co/tiiuae/falcon-40b',
    logo: '/logos/tech/tii-logo.svg',
    category: 'open-source-ai',
    group: 'llms',
  },
  {
    id: 'mpt-30b',
    name: 'MPT-30B',
    organization: 'MosaicML',
    description: 'Production ready',
    link: 'https://huggingface.co/mosaicml/mpt-30b',
    logo: '/logos/tech/cohere-avatar.png',
    category: 'open-source-ai',
    group: 'llms',
  },
  {
    id: 'bloom',
    name: 'BLOOM',
    organization: 'BigScience',
    description: 'Multilingual 176B',
    link: 'https://huggingface.co/bigscience/bloom',
    logo: '/logos/tech/huggingface.svg',
    category: 'open-source-ai',
    group: 'llms',
  },
  {
    id: 'olmo',
    name: 'OLMo',
    organization: 'AI2',
    description: 'Research-first',
    link: 'https://huggingface.co/allenai/OLMo',
    logo: '/logos/tech/salesforce-avatar.png',
    category: 'open-source-ai',
    group: 'llms',
  },
  // Specialized models
  {
    id: 'codellama',
    name: 'Code Llama',
    description: 'Code generation',
    link: 'https://huggingface.co/codellama/CodeLlama-34b',
    logo: '/logos/tech/meta-logo.png',
    category: 'open-source-ai',
    group: 'specialized',
  },
  {
    id: 'stable-lm',
    name: 'Stable LM',
    organization: 'Stability AI',
    description: 'General purpose',
    link: 'https://huggingface.co/stabilityai/stablelm-tuned',
    logo: '/logos/tech/ai21-avatar.png',
    category: 'open-source-ai',
    group: 'specialized',
  },
  {
    id: 'dolphin-mixtral',
    name: 'Dolphin Mixtral',
    organization: 'Cognitive Computations',
    description: 'Instruction tuned',
    link: 'https://huggingface.co/cognitivecomputations/dolphin-2.5-mixtral-8x7b',
    logo: '/logos/tech/gemini-avatar.png',
    category: 'open-source-ai',
    group: 'specialized',
  },
  {
    id: 'yi-34b',
    name: 'Yi 34B',
    organization: '01.AI',
    description: 'General purpose',
    link: 'https://huggingface.co/01-ai/Yi-34B',
    logo: '/logos/tech/claude-avatar.png',
    category: 'open-source-ai',
    group: 'specialized',
  },
  {
    id: 'nous-hermes-2',
    name: 'Nous Hermes 2',
    organization: 'Nous Research',
    description: 'Instruction tuned',
    link: 'https://huggingface.co/NousResearch/Nous-Hermes-2-Mixtral-8x7B',
    logo: '/logos/tech/palm-avatar.png',
    category: 'open-source-ai',
    group: 'specialized',
  },
  // Embeddings
  {
    id: 'sentence-transformers',
    name: 'Sentence Transformers',
    description: 'RAG Baselines',
    link: 'https://huggingface.co/sentence-transformers',
    logo: '/logos/tech/huggingface.svg',
    category: 'open-source-ai',
    group: 'embeddings',
  },
  {
    id: 'bge-embeddings',
    name: 'BGE Large',
    description: 'High recall',
    link: 'https://huggingface.co/BAAI/bge-large-en-v1.5',
    logo: '/logos/tech/sentence-avatar.png',
    category: 'open-source-ai',
    group: 'embeddings',
  },
  {
    id: 'uae-embeddings',
    name: 'UAE-Large',
    description: 'Universal embeddings',
    link: 'https://huggingface.co/WhereIsAI/UAE-Large-V1',
    logo: '/logos/tech/instructor-avatar.png',
    category: 'open-source-ai',
    group: 'embeddings',
  },
  // Vision
  {
    id: 'clip',
    name: 'CLIP',
    organization: 'OpenAI',
    description: 'Vision-language',
    link: 'https://huggingface.co/openai/clip-vit-large-patch14',
    logo: '/logos/tech/openai.svg',
    category: 'open-source-ai',
    group: 'vision',
  },
  {
    id: 'llava',
    name: 'LLaVA',
    description: 'Multimodal assistant',
    link: 'https://huggingface.co/liuhaotian/llava-v1.5-13b',
    logo: '/logos/tech/qwen-avatar.png',
    category: 'open-source-ai',
    group: 'vision',
  },
  {
    id: 'vilbert',
    name: 'ViLBERT',
    description: 'Vision + language',
    link: 'https://huggingface.co/dandelin/ViLBERT-MT-COCO',
    logo: '/logos/tech/nomic-avatar.png',
    category: 'open-source-ai',
    group: 'vision',
  },
  // Section 2 enterprise
  {
    id: 'claude-sonnet',
    name: 'Claude Sonnet',
    organization: 'Anthropic',
    link: 'https://www.anthropic.com',
    description: 'Balanced reasoning',
    logo: '/logos/tech/embedchain-avatar.png',
    category: 'enterprise-models',
  },
  {
    id: 'claude-3-opus',
    name: 'Claude 3 Opus',
    organization: 'Anthropic',
    link: 'https://www.anthropic.com',
    description: 'High accuracy',
    logo: '/logos/tech/embedchain-avatar.png',
    category: 'enterprise-models',
  },
  {
    id: 'gpt-4',
    name: 'GPT-4',
    organization: 'OpenAI',
    link: 'https://openai.com',
    description: 'ChatGPT / API',
    logo: '/logos/tech/openai.svg',
    category: 'enterprise-models',
  },
  {
    id: 'gpt-4-turbo',
    name: 'GPT-4 Turbo',
    organization: 'OpenAI',
    link: 'https://openai.com',
    description: 'Context 128k',
    logo: '/logos/tech/openai.svg',
    category: 'enterprise-models',
  },
  {
    id: 'gemini-pro',
    name: 'Gemini Pro',
    organization: 'Google',
    link: 'https://ai.google.dev',
    description: 'Multimodal API',
    logo: '/logos/tech/google.svg',
    category: 'enterprise-models',
  },
  {
    id: 'gemini-ultra',
    name: 'Gemini Ultra',
    organization: 'Google',
    link: 'https://ai.google.dev',
    description: 'Enterprise tier',
    logo: '/logos/tech/google.svg',
    category: 'enterprise-models',
  },
  // Section 3 frameworks foundation
  {
    id: 'jax',
    name: 'JAX',
    link: 'https://jax.readthedocs.io',
    description: 'High-performance',
    logo: '/logos/tech/jax-avatar.png',
    category: 'frameworks',
    group: 'foundation',
  },
  {
    id: 'transformers',
    name: 'Transformers',
    link: 'https://huggingface.co/transformers',
    description: 'NLP toolkit',
    logo: '/logos/tech/huggingface.svg',
    category: 'frameworks',
    group: 'foundation',
  },
  {
    id: 'langchain',
    name: 'LangChain',
    link: 'https://www.langchain.com',
    description: 'LLM pipelines',
    logo: '/logos/tech/langchain.png',
    category: 'frameworks',
    group: 'llm-app',
  },
  {
    id: 'llamaindex',
    name: 'LlamaIndex',
    link: 'https://www.llamaindex.ai',
    description: 'Data frameworks',
    logo: '/logos/tech/transformers-avatar.png',
    category: 'frameworks',
    group: 'llm-app',
  },
  {
    id: 'semantic-kernel',
    name: 'Semantic Kernel',
    link: 'https://learn.microsoft.com/semantic-kernel',
    description: 'Microsoft OSS',
    logo: '/logos/tech/microsoft-seeklogo.png',
    category: 'frameworks',
    group: 'llm-app',
  },
  {
    id: 'autogen',
    name: 'AutoGen',
    link: 'https://microsoft.github.io/autogen/',
    description: 'Agent orchestration',
    logo: '/logos/tech/microsoft-seeklogo.png',
    category: 'frameworks',
    group: 'llm-app',
  },
  // Backend
  {
    id: 'fastapi',
    name: 'FastAPI',
    link: 'https://fastapi.tiangolo.com',
    description: 'Python APIs',
    logo: '/logos/tech/fastapi.svg',
    category: 'backend',
  },
  {
    id: 'django',
    name: 'Django',
    link: 'https://www.djangoproject.com',
    description: 'Batteries included',
    logo: '/logos/tech/django.svg',
    category: 'backend',
  },
  {
    id: 'flask',
    name: 'Flask',
    link: 'https://flask.palletsprojects.com',
    description: 'Lightweight APIs',
    logo: '/logos/tech/flask.svg',
    category: 'backend',
  },
  {
    id: 'nodejs',
    name: 'Node.js',
    link: 'https://nodejs.org',
    description: 'Event-driven runtime',
    logo: '/logos/tech/nodejs.svg',
    category: 'backend',
  },
  {
    id: 'express',
    name: 'Express.js',
    link: 'https://expressjs.com',
    description: 'Minimal API framework',
    logo: '/logos/tech/express.svg',
    category: 'backend',
  },
  {
    id: 'nest',
    name: 'NestJS',
    link: 'https://nestjs.com',
    description: 'Structured Node APIs',
    logo: '/logos/tech/nestjs.svg',
    category: 'backend',
  },
  // Databases - relational
  {
    id: 'postgresql',
    name: 'PostgreSQL',
    link: 'https://www.postgresql.org',
    description: 'Primary relational DB',
    logo: '/logos/tech/postgresql.svg',
    category: 'databases',
    group: 'relational',
  },
  {
    id: 'mysql',
    name: 'MySQL',
    link: 'https://www.mysql.com',
    description: 'Reliable & mature',
    logo: '/logos/tech/mysql.svg',
    category: 'databases',
    group: 'relational',
  },
  {
    id: 'mariadb',
    name: 'MariaDB',
    link: 'https://mariadb.org',
    description: 'Open MySQL fork',
    logo: '/logos/tech/mariadb.svg',
    category: 'databases',
    group: 'relational',
  },
  // nosql
  {
    id: 'mongodb',
    name: 'MongoDB',
    link: 'https://www.mongodb.com',
    description: 'Document store',
    logo: '/logos/tech/mongodb.svg',
    category: 'databases',
    group: 'nosql',
  },
  {
    id: 'redis',
    name: 'Redis',
    link: 'https://redis.io',
    description: 'In-memory cache',
    logo: '/logos/tech/redis.svg',
    category: 'databases',
    group: 'nosql',
  },
  {
    id: 'elasticsearch',
    name: 'Elasticsearch',
    link: 'https://www.elastic.co',
    description: 'Search & analytics',
    logo: '/logos/tech/elasticsearch.svg',
    category: 'databases',
    group: 'nosql',
  },
  // vector
  {
    id: 'pinecone',
    name: 'Pinecone',
    link: 'https://www.pinecone.io',
    description: 'Managed vector DB',
    logo: '/logos/tech/pinecone.svg',
    category: 'databases',
    group: 'vector',
  },
  {
    id: 'weaviate',
    name: 'Weaviate',
    link: 'https://weaviate.io',
    description: 'Hybrid search',
    logo: '/logos/tech/langchain-avatar.png',
    category: 'databases',
    group: 'vector',
  },
  {
    id: 'milvus',
    name: 'Milvus',
    link: 'https://milvus.io',
    description: 'Open source vector store',
    logo: '/logos/tech/haystack-avatar.png',
    category: 'databases',
    group: 'vector',
  },
  {
    id: 'qdrant',
    name: 'Qdrant',
    link: 'https://qdrant.tech',
    description: 'Rust-based vector DB',
    logo: '/logos/tech/crewai-avatar.png',
    category: 'databases',
    group: 'vector',
  },
  // Frontend
  {
    id: 'react',
    name: 'React',
    link: 'https://react.dev',
    description: 'UI Library',
    logo: '/logos/tech/react.svg',
    category: 'frontend',
  },
  {
    id: 'vue',
    name: 'Vue.js',
    link: 'https://vuejs.org',
    description: 'Progressive framework',
    logo: '/logos/tech/vuejs.svg',
    category: 'frontend',
  },
  {
    id: 'typescript',
    name: 'TypeScript',
    link: 'https://www.typescriptlang.org',
    description: 'Typed JS',
    logo: '/logos/tech/typescript.svg',
    category: 'frontend',
  },
  {
    id: 'javascript',
    name: 'JavaScript',
    link: 'https://developer.mozilla.org/docs/Web/JavaScript',
    description: 'Language of the web',
    logo: '/logos/tech/javascript.svg',
    category: 'frontend',
  },
  {
    id: 'tailwindcss',
    name: 'Tailwind CSS',
    link: 'https://tailwindcss.com',
    description: 'Utility-first CSS',
    logo: '/logos/tech/tailwindcss.svg',
    category: 'frontend',
  },
  {
    id: 'nextjs',
    name: 'Next.js',
    link: 'https://nextjs.org',
    description: 'React meta-framework',
    logo: '/logos/tech/nextjs.svg',
    category: 'frontend',
  },
  // Infrastructure
  {
    id: 'docker',
    name: 'Docker',
    link: 'https://www.docker.com',
    description: 'Container runtime',
    logo: '/logos/tech/docker.svg',
    category: 'infrastructure',
  },
  {
    id: 'kubernetes',
    name: 'Kubernetes',
    link: 'https://kubernetes.io',
    description: 'Container orchestration',
    logo: '/logos/tech/kubernetes.svg',
    category: 'infrastructure',
  },
  {
    id: 'aws',
    name: 'AWS',
    link: 'https://aws.amazon.com',
    description: 'Global cloud',
    logo: '/logos/tech/aws.svg',
    category: 'infrastructure',
  },
  {
    id: 'gcp',
    name: 'Google Cloud',
    link: 'https://cloud.google.com',
    description: 'Data & AI cloud',
    logo: '/logos/tech/gcp.svg',
    category: 'infrastructure',
  },
  {
    id: 'azure',
    name: 'Microsoft Azure',
    link: 'https://azure.microsoft.com',
    description: 'Enterprise cloud',
    logo: '/logos/tech/azure.svg',
    category: 'infrastructure',
  },
  {
    id: 'digitalocean',
    name: 'DigitalOcean',
    link: 'https://www.digitalocean.com',
    description: 'Lean cloud',
    logo: '/logos/tech/digitalocean.svg',
    category: 'infrastructure',
  },
  // Data & workflows
  {
    id: 'temporal',
    name: 'Temporal',
    link: 'https://temporal.io',
    description: 'Workflow engine',
    logo: '/logos/tech/temporal.png',
    category: 'data-workflows',
  },
  {
    id: 'airflow',
    name: 'Apache Airflow',
    link: 'https://airflow.apache.org',
    description: 'Data pipelines',
    logo: '/logos/tech/airflow.png',
    category: 'data-workflows',
  },
  {
    id: 'celery',
    name: 'Celery',
    link: 'https://docs.celeryq.dev',
    description: 'Task queues',
    logo: '/logos/tech/prefect-avatar.png',
    category: 'data-workflows',
  },
  {
    id: 'dagster',
    name: 'Dagster',
    link: 'https://dagster.io',
    description: 'Modern orchestration',
    logo: '/logos/tech/dagster-avatar.png',
    category: 'data-workflows',
  },
  // BaaS & Platforms
  {
    id: 'supabase',
    name: 'Supabase',
    link: 'https://supabase.com',
    description: 'Open Firebase alt',
    logo: '/logos/tech/supabase.svg',
    category: 'baas-platforms',
  },
  {
    id: 'firebase',
    name: 'Firebase',
    link: 'https://firebase.google.com',
    description: 'Realtime backend',
    logo: '/logos/tech/firebase.svg',
    category: 'baas-platforms',
  },
  {
    id: 'corteza',
    name: 'Corteza',
    link: 'https://www.cortezaproject.org',
    description: 'Open CRM / ERP',
    logo: '/logos/tech/corteza.png',
    category: 'baas-platforms',
  },
  {
    id: 'strapi',
    name: 'Strapi',
    link: 'https://strapi.io',
    description: 'Headless CMS',
    logo: '/logos/tech/strapi.svg',
    category: 'baas-platforms',
  },
  // Developer tools
  {
    id: 'git',
    name: 'Git',
    link: 'https://git-scm.com',
    description: 'Version control',
    logo: '/logos/tech/git.svg',
    category: 'dev-tools',
  },
  {
    id: 'github',
    name: 'GitHub',
    link: 'https://github.com',
    description: 'Collaboration',
    logo: '/logos/tech/github.svg',
    category: 'dev-tools',
  },
  {
    id: 'gitlab',
    name: 'GitLab',
    link: 'https://gitlab.com',
    description: 'CI/CD Platform',
    logo: '/logos/tech/gitlab.svg',
    category: 'dev-tools',
  },
  {
    id: 'docker-hub',
    name: 'Docker Hub',
    link: 'https://hub.docker.com',
    description: 'Image registry',
    logo: '/logos/tech/docker.svg',
    category: 'dev-tools',
  },
  {
    id: 'npm',
    name: 'npm',
    link: 'https://www.npmjs.com',
    description: 'JavaScript packages',
    logo: '/logos/tech/npm-original-wordmark.svg',
    category: 'dev-tools',
  },
  {
    id: 'pip',
    name: 'pip',
    link: 'https://pypi.org',
    description: 'Python packages',
    logo: '/logos/tech/python.svg',
    category: 'dev-tools',
  },
]
